# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab31373b82177e75fcd35e26e0dbc76ede3f34d3866befae6a82693b1a7448acea23469a1ef7f788a75bb36cad75ae8cb32008207298963268dc86f2e1a35cd4

test:
  secret_key_base: 13def9dcf4df666cb9899bd94407cde02842e0dfd427f7b1b37ef8c6164ea3bf1f5926640d3b610fc9eee0299c5746868c1029670cdfca59df1905356b4c32d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
